### ISSUE TITLE
Strawberry: Re-installing PDL::Drawing::Prima after PDL upgrade fails

### ISSUE THREAD

**Issue by HaraldJoerg** [dk/PDL-Drawing-Prima#46]
On Strawberry Perl, I tried to reinstall PDL::Drawing::Prima after upgrading PDL to 2.100.
`t\00-load-main.t` fails:

```
D:\test\pdl-drawing-prima>perl -Mblib t\00-load-main.t
1..1
not ok 1 - use PDL::Drawing::Prima;
#   Failed test 'use PDL::Drawing::Prima;'
#   at t\00-load-main.t line 8.
#     Tried to use 'PDL::Drawing::Prima'.
#     Error:  Can't load 'D:\test\pdl-drawing-prima\blib\arch/auto/PDL/Drawing/Prima/Prima.xs.dll' for module PDL::Drawing::Prima: load_file:Die angegebene Prozedur wurde nicht gefunden at D:/Perls/5.38-PDL/perl/lib/DynaLoader.pm line 206.
#  at t\00-load-main.t line 8.
# Compilation failed in require at t\00-load-main.t line 8.
# BEGIN failed--compilation aborted at t\00-load-main.t line 8.
Bail out!  Unable to load PDL::Drawing::Prima!
```

A windows dialog box complains over a missing entry "apc_get_core_version" in DLL `D:\test\pdl-drawing-prima\blib\arch\auto\PDL\Drawing\Prima\Prima.xs.dll`
Unfortunately I have no idea where to look further...

**Comment by HaraldJoerg** [comment]
I had another installation problem for PDL 2.100 itself which I could solve by changing Makefile.PL options.
So I tried for this repository as well, and indeed:
```
gmake clean
perl Makefile.PL OPTIMIZE=-g
gmake
gmake test
gmake install

```...everything went smooth, all tests pass.  So this might be another quirk in my Strawberry setup, and I close this issue.
